on: push
name: deploy
jobs:
  deploy:
    name: deploy to eks cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to eks cluster
      uses: ./
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
      with:
        args: kubectl config get-contexts && docker version
